modLoader="kotlinforforge"
loaderVersion="[1.12,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "voidlands"
version = "${version}"
displayName = "Voidlands"
authors = "ReMod Studios"
description = '''
A Mod that aims to expand the surface beneath the Void!
'''
#logoFile = ""

[[dependencies.voidlands]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.voidlands]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.voidlands]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.voidlands]]
modId = "remodcore"
mandatory = true
versionRange = "[0.1.3,)"
ordering = "AFTER"
side = "BOTH"
